title: Blog
author: Time HE:labs
pygments: true
permalink: /blog/:year/:month/:day/:title/
markdown: rdiscount
paginate: 9
paginate_path: "/blog/page:num"
exclude:
 - unicorn.rb
 - README.md
 - Procfile
 - Gemfile
 - Gemfile.lock
 - config.ru
 - vendor
 - sass
 - config.rb
